### ISSUE TITLE
Credentials Leaked

### ISSUE THREAD

**Issue by csquared** [yasir-saeed/Shopify-Intern-Backend-Challenge-Winter-2021#1]
https://github.com/yasir-saeed/Shopify-Intern-Backend-Challenge-Winter-2021/blob/0525f2a5756601a5c467be7152df22d92d5d4659/config/storage.yml#L11-L14 

Hi There:
Chris from Bucketeer. These credentials need to be private! I've rolled the keys for your heroku app to avoid anyone taking control of your bucket.
Cheers,
Chris

**Comment by yasir-saeed** [comment]
changed them to environment variables and rolled it back again just to be safe. Thank you!
